language: node
sudo: false
nvm:
  - 10.16.0

before_install: npm install -g sass
install: npm install
script: npm run deploy

# branches:
#   only:
#     - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true