language: node
sudo: false
nvm:
  - 10.16.0

before_install: npm install -g sass
install: npm install
script: npm run deploy

branches:
  only:
    - master

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: "$GITHUB_TOKEN"
